### ISSUE TITLE
java.lang.RuntimeException: Failed to extract resourceId from command

### ISSUE THREAD

**Issue by philipptrenz** [retel-io/ari-proxy#65]
# Bug Report

corresponding commit-id: latest of master branch
asterisk version: 17.9.4
kafka version: 2.7
java version: openjdk8

## setup description

Docker Compose configuration with following nodes:

- Zookeeper
- 3 Kafka nodes
- Redis node
- Asterisk node
- ari-proxy node 

## failure description

For testing, I wanted to play an audio file on an incoming call. Therefore I answer the incoming call on `STASIS_START`, using a randomly generated `command_id`, with the following:

```python
producer = KafkaProducer(bootstrap_servers=['localhost:9093'], value_serializer=lambda v: json.dumps(v).encode('utf-8'))

producer.send('ari-commands-topic', {
	"callContext":call_context,
	"commandId": command_id,
	"ariCommand": {
		"method": "POST",
		"url": f"/channels/{ channel_id }/answer"
	}
})
```

Which works fine. Next I react to the `RESPONSE` of the command above with the following, also using another randomly generated `command_id`:

```python
producer.send('ari-commands-topic', {
	"callContext": call_context,
	"commandId": command_id,
	"ariCommand": {
		"method": "POST",
		"url": f"/channels/{ channel_id }/play",
		"body": {
			"channelId": channel_id, # not sure if required
			"media": "https://example.com/audio.sln16"
		}
	}
})
```

This command  lets ari-proxy fail with the following stacktrace:

```
2021-08-09/16:56:50,120/CEST [INFO] [ari-app-akka.actor.default-dispatcher-6] Materializer - [>>>   ARI RESPONSE] Element: {"type":"RESPONSE","commandsTopic":"ari-commands-topic","payload":{"status_code":204},"callContext":"c72c970c-9c5b-4722-817b-43e15a22045d","resources":[{"type":"CHANNEL","id":"1628521009.17"}],"commandId":"test-1234-26","commandRequest":{"method":"POST","url":"/channels/1628521009.17/answer"}}
2021-08-09/16:56:52,181/CEST [INFO] [ari-app-akka.actor.default-dispatcher-7] Materializer - [>>>   ARI COMMAND] Element: {"callContext": "c72c970c-9c5b-4722-817b-43e15a22045d", "commandId": "test-1234-46", "ariCommand": {"method": "POST", "url": "/channels/1628521009.17/play", "body": {"channelId": "1628521009.17", "media": "https://example.com/audio.sln16"}}}
2021-08-09/16:56:52,185/CEST [ERROR] [ari-app-akka.actor.default-dispatcher-7] ActorSystemImpl - Error in some stage; restarting stream ...
java.lang.IllegalStateException: java.lang.RuntimeException: Failed to extract resourceId from command 'AriCommand[body={"channelId":"1628521009.17","media":"https://example.com/audio.sln16"},method=POST,url=/channels/1628521009.17/play]'
	at io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseKafkaProcessor.lambda$null$7(AriCommandResponseKafkaProcessor.java:125)
	at io.vavr.control.Try.onFailure(Try.java:659)
	at io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseKafkaProcessor.lambda$run$8b4133d7$1(AriCommandResponseKafkaProcessor.java:123)
	at akka.stream.javadsl.Source.$anonfun$map$1(Source.scala:1969)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:52)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.RuntimeException: Failed to extract resourceId from command 'AriCommand[body={"channelId":"1628521009.17","media":"https://example.com/audio.sln16"},method=POST,url=/channels/1628521009.17/play]'
	at io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseProcessing.registerCallContext(AriCommandResponseProcessing.java:32)
	at io.retel.ariproxy.boundary.commandsandresponses.AriCommandResponseKafkaProcessor.lambda$run$8b4133d7$1(AriCommandResponseKafkaProcessor.java:119)
	... 22 more
```

I did some digging in the code, but could not find anything helpful about `resourceId`. 
Am I missing something or how can I investigate this further? 

## expected behaviour description

Should play the provided audio file.

Thanks a lot for your great code base and your help!

**Comment by philipptrenz** [comment]
Alright, after some debugging I figured out that a `play` command expects a `playbackId` either within the `AriCommand` url or body.

For me, this was quite counterintuitive, as it deviates from the ARI specification and is not documented within this project. It is, per se, no bug, but I would suggest to either document this behavior properly or change it, so that `playbackId` is not mandatory for ari-proxy.

I think, in general it would be nice if ids like `playbackId`, but also `commandId`, if not given within the command will get generated within ari-proxy, e.g. using an UUID.
